name = "web-baru"
main = "worker.js"
compatibility_date = "2026-09-08"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "SENSOR_STATE", class_name = "SensorState" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SensorState"]
